import type {NextPage} from 'next';
import Head from 'next/head';
import { Header } from '../components/Header';
import { Typography } from 'antd';

import { Button, DatePicker, Form, Input, Space, version, Row } from 'antd';
import { mainModule } from 'process';
import { useState } from 'react';

const { Title } = Typography;


const Home: NextPage = () =>{
  const [city, setCity] = useState("")
  const [temperature,setTemperature] = useState(0)
  const [wind, setWind] = useState(0)
  const [resume,setResume] = useState("")
  const [description,setDescription] = useState("")


const callApi = () => {
  fetch(`https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=7c6a959f5ad058e3e406fb96bc4acfdc`)
    .then(res => res.json())
    .then(data => { 
      const temperature = data.main.temp
      const wind = (data.wind.speed * 3600) / 1000
      const resume = (data.weather[0].main).toUpperCase()
      const description = data.weather[0].description
      setTemperature(temperature)
      setWind(wind)
      setResume(resume)
      setDescription(description)
    })
}


  return (
    <>
      <Head>
        <title>Weather APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>{"What's the Weather"}</Header>
      <Title level={2} style={{color: "white"}}>Select a date to see the weather</Title>
      <Space direction="vertical" size="middle" style={{ display: 'flex' }}>
        <Space>
          <DatePicker />
          <Button type="primary" style={{ marginLeft: 8 }}>
            Date
          </Button>
        </Space>
        <Space>
          <Form layout='horizontal'>
            <Space>
              <Space direction='vertical'>
                <Title level={2} style={{color: "white"}}>Select a City</Title>
                <Form.Item style={{color: 'white'}}>
                  <Input placeholder='Search a City' style={{ width: 300}} onChange={(event) => setCity(event.target.value)}/>
                  <Button type='primary' style={{ marginLeft: 8 }} onClick={callApi}>Search</Button>
                </Form.Item>
              </Space>
            </Space>
          </Form>
        </Space>
      </Space>
      {temperature ? (
        <div>
        <p className='city-title' style={{color: '#7928ca'}}>{city.toUpperCase()}</p>
        <p className='temperature'>{temperature} °C</p>
        <p className='wind'>Wind at this moment is {wind} km/h</p>
        <p className='resume'>{resume}</p>
        <p className='description'>{description}</p>
        </div>
      ) : ""}
    </>
  );
};

export default Home;

