import type { NextPage } from 'next';
import Head from 'next/head';
import { Header } from '../components/Header';

import { Button, DatePicker, version } from 'antd';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>{"What's the Weather"}</Header>
      <DatePicker />
      <Button type="primary" style={{ marginLeft: 8 }}>
        Primary Button
      </Button>
    </div>
  );
};

export default Home;
