import type { NextPage } from 'next';
import Head from 'next/head';
import { Header } from '../components/Header';
import { Typography } from 'antd';

import { Button, DatePicker, Form, Input, Space, version, Row } from 'antd';

const { Title } = Typography;




const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Weather APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>{"What's the Weather"}</Header>
      <Title level={2} style={{color: "white"}}>Select a date to see the weather</Title>
      <Space direction="vertical" size="middle" style={{ display: 'flex' }}>
        <Space>
          <DatePicker />
          <Button type="primary" style={{ marginLeft: 8 }}>
            Date
          </Button>
        </Space>
        <Space>
          <Form layout='horizontal'>
            <Space>
              <Space direction='vertical'>
                <Title level={2} style={{color: "white"}}>Select a City</Title>
                <Form.Item style={{color: 'white'}}>
                  <Input placeholder='Search a City' style={{ width: 300}}/>
                  <Button type='primary' style={{ marginLeft: 8 }}>Search</Button>
                </Form.Item>
              </Space>
            </Space>
          </Form>
        </Space>
      </Space>
    </div>
  );
};

export default Home;
